baseurl = "http://blog.commerce-experts.com/"
copyright = "Commerce Experts UG"
languageCode = "en-us"
theme = "ghostwriter"
title = "Commerce Experts Blog"
[Permalinks]
post = "/:year/:month/:day/:filename/"
[Taxonomies]
tag = "tags"
[[menu.main]]
name = "Blog"
url = "/"
weight = 6
[[menu.main]]
name = "Startseite"
url = "http://www.commerce-experts.com/"
weight = 1
[[menu.main]]
name = "Schwerpunkte"
url = "http://www.commerce-experts.com/#about"
weight = 2
[[menu.main]]
name = "Team"
url = "http://www.commerce-experts.com/#team"
weight = 3
[[menu.main]]
name = "Partner"
url = "http://www.commerce-experts.com/#parallax4"
weight = 4
[[menu.main]]
name = "Kontakt"
url = "http://www.commerce-experts.com/#contact"
weight = 5
[params]
github = "https://github.com/CommerceExperts"
headline = "CXP Blog"
intro = true
opengraph = true
twitter = "https://twitter.com/Andy_wagner1980"
